// starters/nextjs/src/ui/components/banda/form/BandaForm.tsx
import type { ComponentPropsWithRef, FormEvent } from 'react';
import { FormContext, type FormApi } from '@/ui/forms/useForm';

export type FormGap = 'sm' | 'md' | 'lg';

export interface BandaFormProps extends Omit<ComponentPropsWithRef<'form'>, 'onSubmit'> {
  /**
   * Moteur useForm (Zod) — branche le contexte des smart fields et
   * désactive la validation native (le schéma fait foi).
   */
  form?: FormApi;
  /**
   * Soumission simple sans moteur : valeurs extraites de FormData
   * (champs nommés ; valeurs multiples jointes par «, »).
   * La validation native (required…) reste active.
   */
  onSubmitValues?: (values: Record<string, string>) => void;
  /** Surface carte : contour + padding (formulaires encadrés). */
  card?: boolean;
  /** Espacement vertical entre les champs. @default 'md' */
  gap?: FormGap;
}

const GAP: Record<FormGap, string> = {
  sm: 'gap-3',
  md: 'gap-4',
  lg: 'gap-6',
};

/**
 * Étend <form> natif. Deux régimes, jamais les deux :
 * - `form` (FormApi) pour les formulaires validés Zod + smart fields ;
 * - `onSubmitValues` pour les formulaires simples — les atomes Banda
 *   participent déjà aux formulaires natifs (name), FormData suffit.
 */
export function BandaForm({
  form,
  onSubmitValues,
  card = false,
  gap = 'md',
  className,
  children,
  ...rest
}: BandaFormProps) {
  const handleSimpleSubmit = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    if (!onSubmitValues) return;
    const data = new FormData(event.currentTarget);
    const values: Record<string, string> = {};
    for (const key of new Set(data.keys())) {
      values[key] = data
        .getAll(key)
        .map((entry) => String(entry))
        .join(', ');
    }
    onSubmitValues(values);
  };

  const formElement = (
    <form
      noValidate={form !== undefined}
      onSubmit={form ? form.handleSubmit : handleSimpleSubmit}
      className={[
        'flex flex-col',
        GAP[gap],
        card ? 'rounded-lg border border-banda-border bg-banda-surface p-6' : '',
        className,
      ]
        .filter(Boolean)
        .join(' ')}
      {...rest}
    >
      {children}
    </form>
  );

  return form ? <FormContext value={form}>{formElement}</FormContext> : formElement;
}

// packages/banda-angular/src/ui/components/banda/form/banda-form.component.ts
/**
 * Étend <form> natif — deux régimes :
 * - `onSubmitValues` : valeurs extraites de FormData (champs nommés).
 * - sans gestionnaire : validation native active.
 * Surface carte optionnelle via `card`.
 */
import { ChangeDetectionStrategy, Component, computed, input, output } from '@angular/core';

export type FormGap = 'sm' | 'md' | 'lg';

const GAP: Record<FormGap, string> = {
  sm: 'gap-3',
  md: 'gap-4',
  lg: 'gap-6',
};

@Component({
  selector: 'banda-form',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <form [class]="formClass()" (submit)="onSubmit($event)">
      <ng-content />
    </form>
  `,
})
export class BandaFormComponent {
  readonly card = input<boolean>(false);
  readonly gap = input<FormGap>('md');
  readonly className = input<string>('');

  /** Émis avec les valeurs extraites de FormData. La validation native reste active. */
  readonly submitValues = output<Record<string, string>>();

  protected readonly formClass = computed(() =>
    [
      'flex flex-col',
      GAP[this.gap()],
      this.card() ? 'rounded-lg border border-banda-border bg-banda-surface p-6' : '',
      this.className(),
    ]
      .filter(Boolean)
      .join(' '),
  );

  protected onSubmit(event: Event): void {
    event.preventDefault();
    const form = event.currentTarget as HTMLFormElement;
    const data = new FormData(form);
    const seen = new Set<string>();
    const values: Record<string, string> = {};
    data.forEach((value, key) => {
      if (seen.has(key)) {
        values[key] = `${values[key]}, ${String(value)}`;
      } else {
        values[key] = String(value);
        seen.add(key);
      }
    });
    this.submitValues.emit(values);
  }
}
