// packages/banda-angular/src/ui/components/banda/label/banda-label.component.ts
/** Étend <label> natif. */
import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core';

@Component({
  selector: 'banda-label',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <label [attr.for]="for()" [class]="labelClass()">
      <ng-content />
      @if (required()) {
        <span class="text-banda-danger" aria-hidden="true"> *</span>
      }
    </label>
  `,
})
export class BandaLabelComponent {
  readonly for = input<string | undefined>(undefined);
  readonly required = input<boolean>(false);
  /** Masque visuellement le label tout en le gardant accessible (sr-only). */
  readonly hidden = input<boolean>(false);

  protected readonly labelClass = computed(() =>
    this.hidden()
      ? 'sr-only'
      : 'mb-1 block font-sans text-sm font-medium text-banda-text',
  );
}

// starters/_reference/src/ui/components/banda/label/BandaLabel.tsx
import type { ComponentPropsWithRef } from 'react';

export interface BandaLabelProps extends ComponentPropsWithRef<'label'> {
  required?: boolean | undefined;
  /** Masque visuellement le label tout en le gardant accessible (sr-only). */
  hidden?: boolean | undefined;
}

/** Étend <label> natif. */
export function BandaLabel({ required, hidden = false, className, children, ...rest }: BandaLabelProps) {
  const classes = [
    hidden ? 'sr-only' : 'mb-1 block font-sans text-sm font-medium text-banda-text',
    className,
  ]
    .filter(Boolean)
    .join(' ');

  return (
    <label className={classes} {...rest}>
      {children}
      {required ? (
        <span className="text-banda-danger" aria-hidden="true">
          {' '}
          *
        </span>
      ) : null}
    </label>
  );
}
