// packages/banda-react/src/ui/components/banda/dropdown-menu/BandaDropdownMenu.tsx
import { createContext, useContext, useEffect, useId } from 'react';
import type { KeyboardEvent, ReactNode } from 'react';
import { createPortal } from 'react-dom';
import { Check, type LucideIcon } from 'lucide-react';
import { useAnchoredDropdown } from '../../../hooks/useAnchoredDropdown';

/* ── Contexte interne : fermeture au choix d'un item ─────────────────── */

interface MenuContextValue {
  close: () => void;
}

const MenuContext = createContext<MenuContextValue | null>(null);

function useMenuContext(): MenuContextValue {
  const context = useContext(MenuContext);
  if (context === null) {
    throw new Error('Les items de menu doivent être rendus sous <BandaDropdownMenu>.');
  }
  return context;
}

/* ── Base : déclencheur + <menu role="menu"> portalé ─────────────────── */

export interface BandaDropdownMenuProps {
  /** Contenu du déclencheur (texte, avatar, icône…). */
  trigger: ReactNode;
  /** Libellé accessible du menu. */
  label: string;
  /** Bord d'alignement du panneau. @default 'start' */
  align?: 'start' | 'end';
  /** Animation d'ouverture (keyframes du preset). */
  animation?: 'slide' | 'zoom';
  /** Classes du déclencheur — remplace le style par défaut si fourni. */
  triggerClassName?: string;
  menuClassName?: string;
  children: ReactNode;
}

const DEFAULT_TRIGGER =
  'inline-flex items-center gap-2 rounded-md bg-banda-surface-muted px-3 py-2 ' +
  'font-sans text-sm font-medium text-banda-text transition-colors duration-fast ' +
  'hover:bg-banda-border focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-banda-focus-ring';

const MENU_ITEM_SELECTOR = '[role^="menuitem"]:not([disabled])';

export function BandaDropdownMenu({
  trigger,
  label,
  align = 'start',
  animation,
  triggerClassName,
  menuClassName,
  children,
}: BandaDropdownMenuProps) {
  const { open, setOpen, triggerRef, listRef, style } = useAnchoredDropdown<HTMLMenuElement>({ align });
  const menuId = useId();

  const close = () => {
    setOpen(false);
    triggerRef.current?.focus();
  };

  /** Focus roving : flèches haut/bas entre les items, boucle aux extrémités. */
  const moveFocus = (direction: 1 | -1) => {
    const items = Array.from(
      listRef.current?.querySelectorAll<HTMLElement>(MENU_ITEM_SELECTOR) ?? [],
    );
    if (items.length === 0) return;
    const activeIndex = items.findIndex((item) => item === document.activeElement);
    const nextIndex = (activeIndex + direction + items.length) % items.length;
    items[nextIndex]?.focus();
  };

  const onMenuKeyDown = (event: KeyboardEvent<HTMLMenuElement>) => {
    switch (event.key) {
      case 'ArrowDown':
        event.preventDefault();
        moveFocus(1);
        break;
      case 'ArrowUp':
        event.preventDefault();
        moveFocus(-1);
        break;
      case 'Escape':
      case 'Tab':
        event.preventDefault();
        close();
        break;
      default:
        break;
    }
  };

  /* Focus initial sur le premier item à l'ouverture. */
  useEffect(() => {
    if (!open) return;
    listRef.current?.querySelector<HTMLElement>(MENU_ITEM_SELECTOR)?.focus();
  }, [open, listRef]);

  return (
    <MenuContext value={{ close }}>
      <button
        ref={triggerRef}
        type="button"
        aria-haspopup="menu"
        aria-expanded={open}
        aria-controls={open ? menuId : undefined}
        onClick={() => setOpen(!open)}
        onKeyDown={(event) => {
          if (event.key === 'ArrowDown' && !open) {
            event.preventDefault();
            setOpen(true);
          }
        }}
        className={triggerClassName ?? DEFAULT_TRIGGER}
      >
        {trigger}
      </button>
      {open
        ? createPortal(
            <menu
              ref={listRef}
              id={menuId}
              role="menu"
              aria-label={label}
              style={style}
              onKeyDown={onMenuKeyDown}
              className={[
                'z-dropdown m-0 min-w-48 list-none rounded-md border border-banda-border bg-banda-surface p-1 shadow-lg',
                animation === 'slide' ? 'animate-banda-slide-up' : '',
                animation === 'zoom' ? 'animate-banda-zoom-in' : '',
                menuClassName,
              ]
                .filter(Boolean)
                .join(' ')}
            >
              {children}
            </menu>,
            document.body,
          )
        : null}
    </MenuContext>
  );
}

/* ── Items ───────────────────────────────────────────────────────────── */

const ITEM_BASE =
  'flex w-full items-center gap-2 rounded-sm px-2 py-1.5 text-left font-sans text-sm ' +
  'transition-colors duration-fast ' +
  'hover:bg-banda-surface-muted focus-visible:outline-none focus-visible:bg-banda-surface-muted focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-banda-focus-ring ' +
  'disabled:pointer-events-none disabled:opacity-50';

export interface DropdownMenuItemProps {
  icon?: LucideIcon;
  /** Raccourci clavier affiché à droite. */
  shortcut?: string;
  description?: string;
  disabled?: boolean;
  /** Action destructive (Se déconnecter…). */
  danger?: boolean;
  /** Ferme le menu après l'action. @default true */
  closeOnSelect?: boolean;
  onSelect?: () => void;
  children: ReactNode;
}

function MenuItem({
  icon: Icon,
  shortcut,
  description,
  disabled,
  danger = false,
  closeOnSelect = true,
  onSelect,
  children,
}: DropdownMenuItemProps) {
  const { close } = useMenuContext();
  return (
    <li role="none" className="m-0 list-none p-0">
      <button
        type="button"
        role="menuitem"
        tabIndex={-1}
        disabled={disabled}
        onClick={() => {
          onSelect?.();
          if (closeOnSelect) close();
        }}
        className={[ITEM_BASE, danger ? 'text-banda-danger' : 'text-banda-text'].join(' ')}
      >
        {Icon ? (
          <Icon size={14} className={danger ? 'shrink-0' : 'shrink-0 text-banda-text-muted'} aria-hidden="true" />
        ) : null}
        {description ? (
          <span className="flex min-w-0 flex-col items-start gap-0.5">
            <span className="font-medium">{children}</span>
            <span className="text-xs text-banda-text-muted">{description}</span>
          </span>
        ) : (
          <span className="min-w-0 flex-1">{children}</span>
        )}
        {shortcut ? (
          <kbd className="ml-auto shrink-0 font-sans text-xs tracking-wide text-banda-text-muted">
            {shortcut}
          </kbd>
        ) : null}
      </button>
    </li>
  );
}

export interface DropdownMenuLabelProps {
  children: ReactNode;
}

function MenuLabel({ children }: DropdownMenuLabelProps) {
  return (
    <li role="none" className="m-0 list-none p-0">
      <span className="block px-2 py-1.5 font-sans text-xs font-medium text-banda-text-muted">
        {children}
      </span>
    </li>
  );
}

function MenuSeparator() {
  return (
    <li role="separator" aria-orientation="horizontal" className="m-0 list-none p-0">
      <hr className="my-1 border-banda-border" />
    </li>
  );
}

/* ── Items à état : checkbox & radio ─────────────────────────────────── */

export interface DropdownMenuCheckboxItemProps {
  checked: boolean;
  onCheckedChange?: (checked: boolean) => void;
  disabled?: boolean;
  children: ReactNode;
}

/** Item à coche — ne ferme pas le menu (réglages multiples). */
function MenuCheckboxItem({ checked, onCheckedChange, disabled, children }: DropdownMenuCheckboxItemProps) {
  return (
    <li role="none" className="m-0 list-none p-0">
      <button
        type="button"
        role="menuitemcheckbox"
        aria-checked={checked}
        tabIndex={-1}
        disabled={disabled}
        onClick={() => onCheckedChange?.(!checked)}
        className={`${ITEM_BASE} text-banda-text`}
      >
        <span className="min-w-0 flex-1">{children}</span>
        {checked ? <Check size={14} className="shrink-0" aria-hidden="true" /> : null}
      </button>
    </li>
  );
}

interface RadioGroupContextValue {
  value: string;
  onValueChange?: ((value: string) => void) | undefined;
}

const RadioGroupContext = createContext<RadioGroupContextValue | null>(null);

export interface DropdownMenuRadioGroupProps {
  value: string;
  onValueChange?: (value: string) => void;
  /** Libellé du groupe, affiché en en-tête. */
  label?: string;
  children: ReactNode;
}

function MenuRadioGroup({ value, onValueChange, label, children }: DropdownMenuRadioGroupProps) {
  return (
    <RadioGroupContext value={{ value, onValueChange }}>
      {label ? <MenuLabel>{label}</MenuLabel> : null}
      {children}
    </RadioGroupContext>
  );
}

export interface DropdownMenuRadioItemProps {
  value: string;
  disabled?: boolean;
  children: ReactNode;
}

/** Item radio — choix exclusif, ne ferme pas le menu. */
function MenuRadioItem({ value, disabled, children }: DropdownMenuRadioItemProps) {
  const group = useContext(RadioGroupContext);
  if (group === null) {
    throw new Error('<BandaDropdownMenu.RadioItem> doit être rendu sous <BandaDropdownMenu.RadioGroup>.');
  }
  const selected = group.value === value;
  return (
    <li role="none" className="m-0 list-none p-0">
      <button
        type="button"
        role="menuitemradio"
        aria-checked={selected}
        tabIndex={-1}
        disabled={disabled}
        onClick={() => group.onValueChange?.(value)}
        className={`${ITEM_BASE} text-banda-text`}
      >
        <span className="min-w-0 flex-1">{children}</span>
        {selected ? <Check size={14} className="shrink-0" aria-hidden="true" /> : null}
      </button>
    </li>
  );
}

/* Pattern composé : BandaDropdownMenu.Item / .Label / .Separator / .CheckboxItem / .RadioGroup / .RadioItem */
BandaDropdownMenu.Item = MenuItem;
BandaDropdownMenu.Label = MenuLabel;
BandaDropdownMenu.Separator = MenuSeparator;
BandaDropdownMenu.CheckboxItem = MenuCheckboxItem;
BandaDropdownMenu.RadioGroup = MenuRadioGroup;
BandaDropdownMenu.RadioItem = MenuRadioItem;

// packages/banda-angular/src/ui/components/banda/dropdown-menu/banda-dropdown-menu.component.ts
/**
 * Menu déroulant accessible (APG « Menu Button ») — pattern composé :
 * BandaDropdownMenuComponent, BandaMenuItemComponent, BandaMenuLabelComponent,
 * BandaMenuSeparatorComponent, BandaMenuCheckboxItemComponent,
 * BandaMenuRadioGroupComponent, BandaMenuRadioItemComponent.
 *
 * Les items injectent BandaDropdownMenuComponent pour appeler close().
 * Les radio items injectent BandaMenuRadioGroupComponent pour lire/écrire la valeur.
 */
import {
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  HostListener,
  ViewChild,
  computed,
  inject,
  input,
  output,
  signal,
} from '@angular/core';
import { type LucideIconData, LucideAngularModule, Check } from 'lucide-angular';

const DEFAULT_TRIGGER =
  'inline-flex items-center gap-2 rounded-md bg-banda-surface-muted px-3 py-2 ' +
  'font-sans text-sm font-medium text-banda-text transition-colors duration-fast ' +
  'hover:bg-banda-border focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-banda-focus-ring';

const ITEM_BASE =
  'flex w-full items-center gap-2 rounded-sm px-2 py-1.5 text-left font-sans text-sm ' +
  'transition-colors duration-fast ' +
  'hover:bg-banda-surface-muted focus-visible:outline-none focus-visible:bg-banda-surface-muted focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-banda-focus-ring ' +
  'disabled:pointer-events-none disabled:opacity-50';

const MENU_ITEM_SELECTOR = '[role^="menuitem"]:not([disabled])';

let uid = 0;

// ─── Menu principal ───────────────────────────────────────────────────────────

@Component({
  selector: 'banda-dropdown-menu',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [LucideAngularModule],
  template: `
    <button
      #triggerRef
      type="button"
      aria-haspopup="menu"
      [attr.aria-expanded]="open()"
      [attr.aria-controls]="open() ? menuId : null"
      [class]="triggerClassName() ?? DEFAULT_TRIGGER"
      (click)="toggle()"
      (keydown)="onTriggerKeyDown($event)"
    >
      <ng-content select="[slot=trigger]" />
    </button>
    @if (open()) {
      <menu
        #menuRef
        [id]="menuId"
        role="menu"
        [attr.aria-label]="label()"
        [style.position]="'fixed'"
        [style.top.px]="menuTop()"
        [style.left.px]="menuLeft()"
        [style.min-width.px]="menuMinWidth()"
        [class]="menuClass()"
        (keydown)="onMenuKeyDown($event)"
      >
        <ng-content />
      </menu>
    }
  `,
})
export class BandaDropdownMenuComponent {
  @ViewChild('triggerRef') triggerRef!: ElementRef<HTMLButtonElement>;
  @ViewChild('menuRef') menuRef?: ElementRef<HTMLMenuElement>;

  readonly label = input.required<string>();
  readonly align = input<'start' | 'end'>('start');
  readonly animation = input<'slide' | 'zoom' | undefined>(undefined);
  readonly triggerClassName = input<string | undefined>(undefined);
  readonly menuClassName = input<string>('');

  protected readonly DEFAULT_TRIGGER = DEFAULT_TRIGGER;
  protected readonly open = signal(false);
  protected readonly menuTop = signal(0);
  protected readonly menuLeft = signal(0);
  protected readonly menuMinWidth = signal(192);

  readonly menuId = `banda-menu-${++uid}`;

  protected readonly menuClass = computed(() =>
    [
      'z-dropdown m-0 min-w-48 list-none rounded-md border border-banda-border bg-banda-surface p-1 shadow-lg',
      this.animation() === 'slide' ? 'animate-banda-slide-up' : '',
      this.animation() === 'zoom' ? 'animate-banda-zoom-in' : '',
      this.menuClassName(),
    ]
      .filter(Boolean)
      .join(' '),
  );

  close(): void {
    this.open.set(false);
    this.triggerRef?.nativeElement?.focus();
  }

  toggle(): void {
    if (this.open()) {
      this.close();
      return;
    }
    const rect = this.triggerRef?.nativeElement?.getBoundingClientRect();
    if (rect) {
      this.menuTop.set(rect.bottom + 4);
      this.menuLeft.set(this.align() === 'end' ? rect.right - 192 : rect.left);
      this.menuMinWidth.set(rect.width);
    }
    this.open.set(true);
    // Focus sur le premier item après rendu.
    setTimeout(() => {
      this.menuRef?.nativeElement
        ?.querySelector<HTMLElement>(MENU_ITEM_SELECTOR)
        ?.focus();
    });
  }

  private moveFocus(direction: 1 | -1): void {
    const items = Array.from(
      this.menuRef?.nativeElement?.querySelectorAll<HTMLElement>(MENU_ITEM_SELECTOR) ?? [],
    );
    if (items.length === 0) return;
    const idx = items.findIndex((item) => item === document.activeElement);
    items[(idx + direction + items.length) % items.length]?.focus();
  }

  protected onTriggerKeyDown(event: KeyboardEvent): void {
    if (event.key === 'ArrowDown' && !this.open()) {
      event.preventDefault();
      this.toggle();
    }
  }

  protected onMenuKeyDown(event: KeyboardEvent): void {
    switch (event.key) {
      case 'ArrowDown': event.preventDefault(); this.moveFocus(1); break;
      case 'ArrowUp': event.preventDefault(); this.moveFocus(-1); break;
      case 'Escape': case 'Tab': event.preventDefault(); this.close(); break;
    }
  }

  @HostListener('document:click', ['$event'])
  onDocumentClick(event: MouseEvent): void {
    if (!this.open()) return;
    if (!this.triggerRef?.nativeElement?.contains(event.target as Node)) {
      this.open.set(false);
    }
  }
}

// ─── Item action ─────────────────────────────────────────────────────────────

@Component({
  selector: 'banda-menu-item',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [LucideAngularModule],
  template: `
    <li role="none" class="m-0 list-none p-0">
      <button
        type="button"
        role="menuitem"
        tabindex="-1"
        [disabled]="disabled() || null"
        [class]="ITEM_BASE + ' ' + (danger() ? 'text-banda-danger' : 'text-banda-text')"
        (click)="onSelect()"
      >
        @if (icon()) {
          <lucide-angular [img]="icon()!" [size]="14"
            [class]="danger() ? 'shrink-0' : 'shrink-0 text-banda-text-muted'"
            aria-hidden="true" />
        }
        @if (description()) {
          <span class="flex min-w-0 flex-col items-start gap-0.5">
            <span class="font-medium"><ng-content /></span>
            <span class="text-xs text-banda-text-muted">{{ description() }}</span>
          </span>
        } @else {
          <span class="min-w-0 flex-1"><ng-content /></span>
        }
        @if (shortcut()) {
          <kbd class="ml-auto shrink-0 font-sans text-xs tracking-wide text-banda-text-muted">{{ shortcut() }}</kbd>
        }
      </button>
    </li>
  `,
})
export class BandaMenuItemComponent {
  private readonly menu = inject(BandaDropdownMenuComponent);

  readonly icon = input<LucideIconData | undefined>(undefined);
  readonly shortcut = input<string | undefined>(undefined);
  readonly description = input<string | undefined>(undefined);
  readonly disabled = input<boolean>(false);
  readonly danger = input<boolean>(false);
  readonly closeOnSelect = input<boolean>(true);
  readonly select = output<void>();

  protected readonly ITEM_BASE = ITEM_BASE;

  protected onSelect(): void {
    this.select.emit();
    if (this.closeOnSelect()) this.menu.close();
  }
}

// ─── Label de groupe ──────────────────────────────────────────────────────────

@Component({
  selector: 'banda-menu-label',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <li role="none" class="m-0 list-none p-0">
      <span class="block px-2 py-1.5 font-sans text-xs font-medium text-banda-text-muted">
        <ng-content />
      </span>
    </li>
  `,
})
export class BandaMenuLabelComponent {}

// ─── Séparateur ───────────────────────────────────────────────────────────────

@Component({
  selector: 'banda-menu-separator',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <li role="separator" aria-orientation="horizontal" class="m-0 list-none p-0">
      <hr class="my-1 border-banda-border" />
    </li>
  `,
})
export class BandaMenuSeparatorComponent {}

// ─── Item à coche ─────────────────────────────────────────────────────────────

@Component({
  selector: 'banda-menu-checkbox-item',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [LucideAngularModule],
  template: `
    <li role="none" class="m-0 list-none p-0">
      <button
        type="button"
        role="menuitemcheckbox"
        [attr.aria-checked]="checked()"
        tabindex="-1"
        [disabled]="disabled() || null"
        [class]="ITEM_BASE + ' text-banda-text'"
        (click)="checkedChange.emit(!checked())"
      >
        <span class="min-w-0 flex-1"><ng-content /></span>
        @if (checked()) {
          <lucide-angular [img]="Check" [size]="14" class="shrink-0" aria-hidden="true" />
        }
      </button>
    </li>
  `,
})
export class BandaMenuCheckboxItemComponent {
  readonly checked = input.required<boolean>();
  readonly disabled = input<boolean>(false);
  readonly checkedChange = output<boolean>();

  protected readonly ITEM_BASE = ITEM_BASE;
  protected readonly Check = Check;
}

// ─── Groupe radio ─────────────────────────────────────────────────────────────

@Component({
  selector: 'banda-menu-radio-group',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [BandaMenuLabelComponent],
  template: `
    @if (label()) {
      <banda-menu-label>{{ label() }}</banda-menu-label>
    }
    <ng-content />
  `,
})
export class BandaMenuRadioGroupComponent {
  readonly value = input.required<string>();
  readonly label = input<string | undefined>(undefined);
  readonly valueChange = output<string>();

  /** Appelé par les items enfants. */
  notifyChange(val: string): void {
    this.valueChange.emit(val);
  }
}

// ─── Item radio ───────────────────────────────────────────────────────────────

@Component({
  selector: 'banda-menu-radio-item',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [LucideAngularModule],
  template: `
    <li role="none" class="m-0 list-none p-0">
      <button
        type="button"
        role="menuitemradio"
        [attr.aria-checked]="isSelected()"
        tabindex="-1"
        [disabled]="disabled() || null"
        [class]="ITEM_BASE + ' text-banda-text'"
        (click)="onSelect()"
      >
        <span class="min-w-0 flex-1"><ng-content /></span>
        @if (isSelected()) {
          <lucide-angular [img]="Check" [size]="14" class="shrink-0" aria-hidden="true" />
        }
      </button>
    </li>
  `,
})
export class BandaMenuRadioItemComponent {
  private readonly group = inject(BandaMenuRadioGroupComponent);

  readonly value = input.required<string>();
  readonly disabled = input<boolean>(false);

  protected readonly ITEM_BASE = ITEM_BASE;
  protected readonly Check = Check;

  protected readonly isSelected = computed(() => this.group.value() === this.value());

  protected onSelect(): void {
    this.group.notifyChange(this.value());
  }
}
