// packages/banda-angular/src/ui/components/banda/card/banda-card.component.ts
/**
 * Conteneur de contenu autonome — pattern composé via sous-composants :
 * BandaCardHeaderComponent / TitleComponent / DescriptionComponent / BodyComponent / FooterComponent / MediaComponent.
 */
import { ChangeDetectionStrategy, Component, input } from '@angular/core';

@Component({
  selector: 'banda-card',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <article [class]="'rounded-lg border border-banda-border bg-banda-surface text-banda-text shadow-sm ' + (className() ?? '')">
      <ng-content />
    </article>
  `,
})
export class BandaCardComponent {
  readonly className = input<string | undefined>(undefined);
}

@Component({
  selector: 'banda-card-header',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <header [class]="'flex flex-col gap-1.5 p-6 ' + (className() ?? '')">
      <ng-content />
    </header>
  `,
})
export class BandaCardHeaderComponent {
  readonly className = input<string | undefined>(undefined);
}

@Component({
  selector: 'banda-card-title',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <h3 [class]="'m-0 font-sans text-lg font-semibold text-banda-text ' + (className() ?? '')">
      <ng-content />
    </h3>
  `,
})
export class BandaCardTitleComponent {
  readonly className = input<string | undefined>(undefined);
}

@Component({
  selector: 'banda-card-description',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <p [class]="'m-0 font-sans text-sm text-banda-text-muted ' + (className() ?? '')">
      <ng-content />
    </p>
  `,
})
export class BandaCardDescriptionComponent {
  readonly className = input<string | undefined>(undefined);
}

@Component({
  selector: 'banda-card-body',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div [class]="'px-6 pb-6 ' + (className() ?? '')">
      <ng-content />
    </div>
  `,
})
export class BandaCardBodyComponent {
  readonly className = input<string | undefined>(undefined);
}

@Component({
  selector: 'banda-card-footer',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <footer [class]="'flex items-center gap-2 px-6 pb-6 ' + (className() ?? '')">
      <ng-content />
    </footer>
  `,
})
export class BandaCardFooterComponent {
  readonly className = input<string | undefined>(undefined);
}

/** Zone média pleine largeur (image, dégradé…) — arrondie en tête de carte. */
@Component({
  selector: 'banda-card-media',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div [class]="'w-full overflow-hidden first:rounded-t-lg ' + (className() ?? '')">
      <ng-content />
    </div>
  `,
})
export class BandaCardMediaComponent {
  readonly className = input<string | undefined>(undefined);
}

// starters/_reference/src/ui/components/banda/card/BandaCard.tsx
import type { ComponentPropsWithRef } from 'react';

function joinClasses(base: string, className?: string) {
  return [base, className].filter(Boolean).join(' ');
}

export type BandaCardProps = ComponentPropsWithRef<'article'>;

/**
 * Étend <article> natif — conteneur de contenu autonome, pattern composé :
 * BandaCard.Header / .Title / .Description / .Body / .Footer.
 */
export function BandaCard({ className, ...rest }: BandaCardProps) {
  return (
    <article
      className={joinClasses(
        'rounded-lg border border-banda-border bg-banda-surface text-banda-text shadow-sm',
        className,
      )}
      {...rest}
    />
  );
}

function CardHeader({ className, ...rest }: ComponentPropsWithRef<'header'>) {
  return <header className={joinClasses('flex flex-col gap-1.5 p-6', className)} {...rest} />;
}

function CardTitle({ className, ...rest }: ComponentPropsWithRef<'h3'>) {
  return (
    <h3
      className={joinClasses('m-0 font-sans text-lg font-semibold text-banda-text', className)}
      {...rest}
    />
  );
}

function CardDescription({ className, ...rest }: ComponentPropsWithRef<'p'>) {
  return (
    <p
      className={joinClasses('m-0 font-sans text-sm text-banda-text-muted', className)}
      {...rest}
    />
  );
}

function CardBody({ className, ...rest }: ComponentPropsWithRef<'div'>) {
  return <div className={joinClasses('px-6 pb-6', className)} {...rest} />;
}

function CardFooter({ className, ...rest }: ComponentPropsWithRef<'footer'>) {
  return (
    <footer className={joinClasses('flex items-center gap-2 px-6 pb-6', className)} {...rest} />
  );
}

/** Zone média pleine largeur (image, dégradé…) — arrondie en tête de carte. */
function CardMedia({ className, ...rest }: ComponentPropsWithRef<'div'>) {
  return (
    <div className={joinClasses('w-full overflow-hidden first:rounded-t-lg', className)} {...rest} />
  );
}

/* Pattern composé : BandaCard.Header / .Title / .Description / .Body / .Footer / .Media */
BandaCard.Header = CardHeader;
BandaCard.Title = CardTitle;
BandaCard.Description = CardDescription;
BandaCard.Body = CardBody;
BandaCard.Footer = CardFooter;
BandaCard.Media = CardMedia;
