// starters/angular/.banda/templates/feature/components/{{FEATURE_NAME}}-view.component.ts
import { ChangeDetectionStrategy, Component, inject } from '@angular/core';
import { {{FeatureName}}Service } from '../services/{{FEATURE_NAME}}.service';

@Component({
  selector: 'app-{{FEATURE_NAME}}-view',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [],
  template: `
    @if (service.isLoading()) {
      <p>Chargement…</p>
    } @else if (service.error()) {
      <p role="alert">{{ service.error() }}</p>
    } @else {
      <section>
        <!-- TODO : implémenter la vue ici -->
      </section>
    }
  `,
})
export class {{FeatureName}}ViewComponent {
  protected readonly service = inject({{FeatureName}}Service);
}

// starters/_reference/.banda/templates/feature/components/{{FeatureName}}View.tsx
import { use{{FeatureName}} } from '../hooks/use{{FeatureName}}';

/**
 * Composant principal de la feature {{FEATURE_NAME}}.
 * Délègue toute la logique à use{{FeatureName}} — reste un composant "bête".
 */
export function {{FeatureName}}View() {
  const { isLoading, error } = use{{FeatureName}}();

  if (isLoading) return <p>Chargement…</p>;
  if (error) return <p role="alert">{error}</p>;

  return (
    <section>
      {/* TODO : implémenter la vue ici */}
    </section>
  );
}
